# Generated by Django 2.2.4 on 2019-09-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=60),
        ),
    ]
